def write_lammps_data(output_filename, template_data, box_size, generated):
    with open(output_filename, 'w') as f:
        f.write("LAMMPS data file generated by Python\n\n")
        f.write(f"{len(generated['atoms'])} atoms\n")
        f.write(f"{len(generated['bonds'])} bonds\n")
        f.write(f"{len(generated['angles'])} angles\n")
        f.write(f"{len(generated['dihedrals'])} dihedrals\n")
        f.write(f"{len(generated['impropers'])} impropers\n\n")

        f.write(f"{template_data['counts']['atom_types']} atom types\n")
        f.write(f"{template_data['counts']['bond_types']} bond types\n")
        f.write(f"{template_data['counts']['angle_types']} angle types\n")
        f.write(f"{template_data['counts']['dihedral_types']} dihedral types\n")
        f.write(f"{template_data['counts']['improper_types']} improper types\n\n")

        f.write(f"{box_size[0]} {box_size[1]} xlo xhi\n")
        f.write(f"{box_size[2]} {box_size[3]} ylo yhi\n")
        f.write(f"{box_size[4]} {box_size[5]} zlo zhi\n\n")

        f.write("Masses\n\n")
        for atom_type in sorted(template_data['masses'].keys()):
            f.write(f"{atom_type} {template_data['masses'][atom_type]:.4f}\n")
        f.write("\n")

        f.write("Atoms # full\n\n")
        for atom in generated['atoms']:
            f.write(f"{atom['id']} {atom['mol']} {atom['type']} {atom['charge']:.4f} "
                    f"{atom['x']:.6f} {atom['y']:.6f} {atom['z']:.6f} "
                    f"{atom['ix']} {atom['iy']} {atom['iz']}\n")
        f.write("\n")

        f.write("Bonds\n\n")
        for bond in generated['bonds']:
            f.write(f"{bond['id']} {bond['type']} {bond['atom1']} {bond['atom2']}\n")
        f.write("\n")

        f.write("Angles\n\n")
        for angle in generated['angles']:
            f.write(f"{angle['id']} {angle['type']} {angle['a1']} {angle['a2']} {angle['a3']}\n")
        f.write("\n")

        f.write("Dihedrals\n\n")
        for dih in generated['dihedrals']:
            f.write(f"{dih['id']} {dih['type']} {dih['a1']} {dih['a2']} {dih['a3']} {dih['a4']}\n")
        f.write("\n")

        f.write("Impropers\n\n")
        for imp in generated['impropers']:
            f.write(f"{imp['id']} {imp['type']} {imp['a1']} {imp['a2']} {imp['a3']} {imp['a4']}\n")
